### ISSUE TITLE
nuxt-ts fails to compile vue files?

### ISSUE THREAD

**Issue by Texlo-Dev** [hmsk/nuxt-ts#5]
I installed nuxt-ts today and I followed the instructions to compile my application. Upon the compilation completing, I am greeted with this error:

```js
✖ error friendly-errors › Failed to compile with 1 errors
✖ error friendly-errors › in ./.nuxt/router.js
❯ log friendly-errors › Module parse failed: Unexpected token (6:24)
You may need an appropriate loader to handle this file type.
|
| var _657f40dc = function _657f40dc() {
>   return interopDefault(import('../client/pages/index.vue'
|   /* webpackChunkName: "pages/index" */
|   ));
❯ log friendly-errors ›
 @ ./.nuxt/index.js 11:0-43 71:19-31
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr/client ./.nuxt/client.js
```

I am not sure why this happens as I am sure that I followed the setup correctly.
I am using nuxt programatically, idk if that influences anything or not.

**Comment by kevinmarrec** [comment]
Hi @Texlo-Dev, if you're using Nuxt programatically you need to either register `ts-node` at the beginning of your code (`require('ts-node').register(options)`) OR run your code with `ts-node server.js` instead of `node server.js`.

The `nuxt-ts-edge` binary does it for you, but as you're not using it by having a programatically setup, you need to do it yourself.

Last thing: the binary also set a `NUXT_TS` environment variable to `'true'` to be able to let Builder you're running in a TypeScript environment en setup the type checking. So you also need to set it yourself either in the script command `NUXT_TS=true ts-node server.js` or right in the code using `process.env.NUXT_TS = 'true'` before building Nuxt.

Sorry if there is no documentation for that yet, the Typescript support is considered as experimental.

**Comment by hmsk** [comment]
Thanks for reporting @Texlo-Dev 
Yeah, the current `nuxt-ts` is not supporting that case. and I'm not going to add because `nuxt-ts` will be owned by Nuxt team soon (from the next minor version, 2.4). Sorry for your confusion.

If you'd like to use current `nuxt-ts` (0.x), as @kevinmarrec says (Thanks too!), require some additional things.
